-- Historical migration record: canonical exercise identity is now live.
-- Current public.solutions identity: (user_id, exercise_type, exercise_number).
-- Allowed exercise_type values: B, C, LC, P, CPP.
-- Legacy problem_id was removed after all production rows were mapped and verified.
-- See Supabase migration history: add_canonical_exercise_identity,
-- promote_canonical_exercise_identity, remove_legacy_problem_id.
